### ISSUE TITLE
Consider renaming of template type name CALLBACK

### ISSUE THREAD

**Issue by arasatalar** [tzaeschke/phtree-cpp#142]
Windows SDK defines "CALLBACK" macro and it leads to compilation errors when used as template type names.  
I propose a simple renaming and attach the patch (only a small part of it) to clarify what I mean. Thanks..

diff --git a/include/phtree/phtree.h b/include/phtree/phtree.h
index 7a418d4..a1516d9 100644
--- a/include/phtree/phtree.h
+++ b/include/phtree/phtree.h
@@ -240,9 +240,9 @@ class PhTree {
      * sub-nodes before they are returned or traversed. Any filter function must follow the
      * signature of the default 'FilterNoOp`.
      */
\-    template <typename CALLBACK, typename FILTER = FilterNoOp>
\-    void for_each(CALLBACK&& callback, FILTER&& filter = FILTER()) const {
\-        tree_.for_each(std::forward<CALLBACK>(callback), std::forward<FILTER>(filter));
\+    template <typename CALLBACK_FN, typename FILTER = FilterNoOp>
\+    void for_each(CALLBACK_FN&& callback, FILTER&& filter = FILTER()) const {
\+        tree_.for_each(std::forward<CALLBACK_FN>(callback), std::forward<FILTER>(filter));

**Comment by tzaeschke** [comment]
Thanks for reporting. I'll have a look.

**Comment by tzaeschke** [comment]
Could you try out this branch?
https://github.com/tzaeschke/phtree-cpp/tree/fix/142-rename-callback-parameter

**Comment by arasatalar** [comment]
Thanks, quick you are. I will try it soon (already tried a very similar one and worked so should be ok).

And for the the NOMINMAX issue, we already added the preprocessor flag to resolve the issue some time ago. Thanks for the info.

**Comment by arasatalar** [comment]
Checked it, seems perfect..  Thanks for the quick response. Best

**Comment by tzaeschke** [comment]
@arasatalar Thanks!
