### ISSUE TITLE
Consider single include File

### ISSUE THREAD

**Issue by joness95** [tzaeschke/phtree-cpp#148]
Hi there,
I'm a huge fan of your work :)
Would it be possible, to create a header only single include file?
This repo seems to only consist of headers, therefor it would be more easy to include it in projects.

**Comment by tzaeschke** [comment]
Thanks!
Yes, this is a header-only library.
Putting all headers into a single file would be possible but would make it hard to maintain and manage. It also simplifies trying out extension where I use some part of the code (e.g. stuff in `common`, but not the rest. It also feels a bit strange to have `PhTree` and `PhTreeMultimap` in the same file when you usually need only one of them. So I am probably not going to do this.

Do you have a specific problem with including it, except for it being multiple files?

I hoped project inclusion would not be too hard, it should be straight forward with bazel/cmake.
With Visual Studio I just copied the whole phtree folder structure into my project and included `phtree.h` which worked fine (even though the folder structure was not shown in the project explorer, instead all files appeared as if in the root folder).

**Comment by joness95** [comment]
For me it was just that in vs i had to add every single file separately ( probably i should update ..).
As for the why:
You don't need to know which file you need to include.
The unused code should be ignored by the compiler and you would have access to all the classes that are not directly included in phtree.h
But I will check it again :)
Thanks for the response btw

**Comment by tzaeschke** [comment]
@joness95 

> Thanks for the response btw

No problem. Let me know if you find any other problem.
